version: '3'

services:
  dbos:
    image: mysql:5.7
    volumes:
      - mysql_storage_1:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 0301
      MYSQL_USER: sahil
      MYSQL_PASSWORD: 0301
      MYSQL_DATABASE: mydb


  wordpressos:
    image: wordpress:5.1.1-php7.3-apache
    restart: always
    depends_on:
      - dbos
    ports:
      - 8081:80
    environment:
      WORDPRESS_DB_HOST: dbos
      WORDPRESS_DB_USER: sahil
      WORDPRESS_DB_PASSWORD: 0301
      WORDPRESS_DB_NAME: mydb
    volumes:
      - wp_storage_1 /var/www/html

volumes:
  wp_storage_1:
  mysql_storage_1:
