#This is for nextcloud

version: '3'

services:
  dbos:
    image: mysql:5.7
    volumes:
      - mysql_storage_2:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 0301
      MYSQL_USER: sahil
      MYSQL_PASSWORD: 0301
      MYSQL_DATABASE: mydb


  nextcloud:
    image: nextcloud:latest
    restart: always
    depends_on:
      - dbos
    ports:
      - 8082:80
    volumes:
      - nc_storage /var/www/html

volumes:
  nc_storage:
  mysql_storage_2: